IMAGE_NAME = "generic/ubuntu2004"
N = 1
IPs = ["", "x.x.x.x"]

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "libvirt" do |v|
        v.memory = 2048
        v.cpus = 4
    end

   (1..N).each do |i|
       config.vm.define "master-#{i}" do |master|
           master.vm.box = IMAGE_NAME
           master.vm.network "public_network", ip: "x.x.x.x", :dev => "enp4s0"
           master.vm.hostname = "master-#{i}"
           master.vm.provision "ansible" do |ansible|
               ansible.playbook = "kubernetes-setup/master-playbook.yml"
               ansible.extra_vars = {
                   node_ip: "x.x.x.x",
               }
           end
       end
    end
end

#    (1..N).each do |i|
#        config.vm.define "node-#{i}" do |node|
#            node.vm.box = IMAGE_NAME
#            node.vm.network "private_network", ip: "10.10.10.#{i + 10}"
#            node.vm.network "public_network", :dev => "br0", :type =>"bridge"
#            node.vm.hostname = "node-#{i}"
#            node.vm.provision "ansible" do |ansible|                           #2
#                ansible.playbook = "kubernetes-setup/node-playbook.yml"        #2
#                ansible.extra_vars = {                                         #2
#                    node_ip: "10.10.10.#{i + 10}",                             #2
#                }                                                              #2
#            end                                                                #2
#        end
#    end
